#!/bin/bash
# on-caso-3-sf (CCX) - limpa artefatos do solver CalculiX.
# Mantem on-caso-3-sf.inp (hand-written); regenera os _{mesh,winkler}.inp no Allrun.

cd "$(dirname "$0")"

echo "Limpando on-caso-3-sf (CCX)..."
rm -f \
    on-caso-3-sf.frd on-caso-3-sf.dat on-caso-3-sf.cvg on-caso-3-sf.sta \
    on-caso-3-sf.12d on-caso-3-sf.eig on-caso-3-sf.txt on-caso-3-sf.rfn.frd \
    on-caso-3-sf.equ on-caso-3-sf.fbd \
    on-caso-3-sf_mesh.inp on-caso-3-sf_winkler.inp \
    on-caso-3-sf.pvd on-caso-3-sf.*.vtu on-caso-3-sf.*.vtk \
    on-caso-3-sf_Pc*.frd on-caso-3-sf_Pc*.dat on-caso-3-sf_Pc*.cvg on-caso-3-sf_Pc*.sta \
    log.ccx log.ccx_Pc* spooles.out
echo "Feito."
