#!/bin/bash
# Limpa todos os artefatos gerados pelo Allrun (mantém os STLs em triSurface/).
set -e
cd solid

# Remove pastas de tempo (mantém 0/)
find . -maxdepth 1 -type d -regex './[0-9].*' ! -name '0' -exec rm -rf {} +

# Remove arquivos gerados pelo snappy / topoSet / createPatch
rm -rf constant/polyMesh
rm -f constant/triSurface/*.eMesh
rm -f log.*
rm -rf 0/include   # se algum dia foram criados

echo "[Allclean] caso artoph-curva-mestrado limpo (triSurface/*.stl preservados)."
