#!/bin/bash
# on-caso-3JS (CCX) - limpa artefatos do solver.
cd "$(dirname "$0")"
echo "Limpando on-caso-3JS (CCX)..."
rm -f \
    on-caso-3JS.frd on-caso-3JS.dat on-caso-3JS.cvg on-caso-3JS.sta \
    on-caso-3JS.12d on-caso-3JS.eig on-caso-3JS.txt on-caso-3JS.rfn.frd \
    on-caso-3JS_mesh.inp on-caso-3JS_winkler.inp on-caso-3JS_dura_orient.inp \
    on-caso-3JS.pvd on-caso-3JS.*.vtu \
    on-caso-3JS_*.frd on-caso-3JS_*.dat on-caso-3JS_*.cvg on-caso-3JS_*.sta \
    log.ccx log.ccx_* spooles.out
echo "Feito."
