#!/bin/bash
# on-caso-3 - limpa resultados (preserva condicoes iniciais em 0/).

cd "$(dirname "$0")/solid"

echo "Limpando on-caso-3 (preservando 0/)..."
rm -rf \
    $(find . -maxdepth 1 -name '[0-9]*' ! -name '0' -type d) \
    log.* \
    postProcessing \
    constant/polyMesh
echo "Feito."
